version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_fred
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fred_data
      MYSQL_USER: freduser
      MYSQL_PASSWORD: fredpass
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - bigdata

  etl:
    build: /etl
    env_file:
      - keys.env
    depends_on:
      - mysql
    networks:
      - bigdata

networks:
  bigdata:
    driver: bridge